### ISSUE TITLE
Initialize the LMCache Backend during model initialization

### ISSUE THREAD

**Issue by qyy2003** [LMCache/lmcache-vllm#20]
Currently, the code checks whether the LMCache Backend has been initialized and initializes it if it hasn’t. It's good to have this check, but it would be better to initialize it when vllm initializes the model.

```
init_lmcache_engine(self.model_config, self.parallel_config)
```

**Comment by XbzOnGit** [comment]
If I understand correctly, new_llm_engine_init in vllm_injection.py in this [PR](https://github.com/LMCache/lmcache-vllm/pull/37) solves this problem. I put it into LLMEngine \_\_init\_\_, which will be called both in online and offline inference.

**Comment by qyy2003** [comment]
Cool, we could close it!
